Line_5 $$ final Exception exception = myRepository.createCancellableConnection().call()-->Line_6 $$ assertNotNull(exception)[ FD ]
Line_2 $$ public void testLogin() throws Exception -->Line_7 $$ assertEquals(TaskBundle.message("failure.login"), exception.getMessage())[ CD ]
Line_5 $$ final Exception exception = myRepository.createCancellableConnection().call()-->Line_7 $$ assertEquals(TaskBundle.message("failure.login"), exception.getMessage())[ FD ]
Line_2 $$ public void testLogin() throws Exception -->Line_5 $$ final Exception exception = myRepository.createCancellableConnection().call()[ CD ]
Line_2 $$ public void testLogin() throws Exception -->Line_6 $$ assertNotNull(exception)[ CD ]
Line_2 $$ public void testLogin() throws Exception -->Line_4 $$ myRepository.setUsername("wrong password")[ CD ]
Line_2 $$ public void testLogin() throws Exception -->Line_3 $$ myRepository.setUsername("german")[ CD ]
