Line_2 $$ public List<Tuple<DiscoveryNode, Throwable>> awaitErrors(long timeout, TimeUnit unit) throws InterruptedException -->Line_3 $$ countDown.await(timeout, unit)[ FD ]
Line_2 $$ public List<Tuple<DiscoveryNode, Throwable>> awaitErrors(long timeout, TimeUnit unit) throws InterruptedException -->Line_3 $$ countDown.await(timeout, unit)[ CD ]
Line_2 $$ public List<Tuple<DiscoveryNode, Throwable>> awaitErrors(long timeout, TimeUnit unit) throws InterruptedException -->Line_5 $$ return errors[ CD ]
Line_2 $$ public List<Tuple<DiscoveryNode, Throwable>> awaitErrors(long timeout, TimeUnit unit) throws InterruptedException -->Line_4 $$ assertFalse(timeoutOccurred.get())[ CD ]
