Line_2 $$ public void testShortOperationsFailure() throws Exception -->Line_3 $$ testOperations(r.nextInt(), 25, 0, false, false, newCall())[ CD ]
