Line_2 $$ public void testOperationProcessCallableFail() -->Line_3 $$ OperationProcessCallable operationProcessCallable = new OperationProcessCallable(_unknowObjectName, "doSomething", new Object[] [ CD ]
Line_3 $$ OperationProcessCallable operationProcessCallable = new OperationProcessCallable(_unknowObjectName, "doSomething", new Object[] -->Line_5 $$ operationProcessCallable.call()[ FD ]
Line_8 $$ Throwable throwable = pe.getCause()-->Line_9 $$ Assert.assertSame(InstanceNotFoundException.class, throwable.getClass())[ FD ]
