Line_2 $$ public void testGetAttributeProcessCallableFailureInstanceNotFound() -->Line_3 $$ GetAttributeProcessCallable getAttributeProcessCallable = new GetAttributeProcessCallable(_unknowObjectName, "Name", true)[ CD ]
Line_3 $$ GetAttributeProcessCallable getAttributeProcessCallable = new GetAttributeProcessCallable(_unknowObjectName, "Name", true)-->Line_5 $$ getAttributeProcessCallable.call()[ FD ]
Line_8 $$ Throwable throwable = pe.getCause()-->Line_9 $$ Assert.assertSame(InstanceNotFoundException.class, throwable.getClass())[ FD ]
